language: python
dist: focal

services:
  - docker

cache: pip

env:
  - SERVER_AUTH_TYPE=basic SERVER_URL=http://127.0.0.1:5984 SERVER_USERNAME=admin SERVER_PASSWORD=password

notifications:
  email: true

matrix:
 include:
   - python: 3.6
   - python: 3.7
   - python: 3.8
   - python: 3.9
   - python: '3.10'

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- bash scripts/setup_couch.sh

install:
- pip install tox-travis

script: tox

# To enable semantic-release, uncomment these sections.
# before_deploy:
# - pip install bump2version
# - nvm install 12
# - npm install @semantic-release/changelog
# - npm install @semantic-release/exec
# - npm install @semantic-release/git
# - npm install @semantic-release/github
#
# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     python: '3.5'
#     branch: master
# - provider: pypi
#   user: __token__
#   password: $PYPI_TOKEN
#   repository: https://upload.pypi.org/legacy
#   skip_cleanup: true
#   on:
#     python: '3.5'
#     tags: true
